# version: "1"
# services:
#   backend:
#     # container_name: story
#     image: story
#     build: 
#       dockerfile: Dockerfile
#       context: .
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_URL: postgres://postgres:user@password:5432/board-app
#       NODE_ENV: development
#       PORT: 3000
#     ports:
#       - "3000:3000"
  
#   postgres:
#     container_name: postgres
#     image: postgres:10.4
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: 'board-app'

# docker-compose.yml
# version: '3'
# services:
#   backend:
#     image: 'coco-dev'
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db
#     environment:
#       - DATABASE_HOST=db
#   #     environment:
# #       DATABASE_URL: postgres://postgres:user@password:5432/board-app
# #       NODE_ENV: development
# #       PORT: 3000
#   db:
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_DATABASE: process.env.MYSQL_DEV_DATABASE
#       MYSQL_USER: process.env.MYSQL_USER
#       MYSQL_PASSWORD: process.env.MYSQL_PASSWORD
#       MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
#     # volumes:
#     #   - db_data:/var/lib/mysql
#     ports:
#       - '3306:3306'
# volumes:
#   db_data: {}


version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: process.env.MYSQL_DEV_DATABASE
      MYSQL_USER: process.env.MYSQL_USER
      MYSQL_PASSWORD: process.env.MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
volumes:
  db_data:
